# Generated by Django 5.1.1 on 2025-03-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='seuil_min',
            new_name='seuil_minimum',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_actuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('MP', 'Matière Première'), ('PF', 'Produit Fini'), ('EM', 'Emballage'), ('OT', 'Autre')], max_length=2),
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.commandeclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('RETOUR', 'Retour')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
    ]
